DROP TABLE IF EXISTS phones;

CREATE TABLE phones (
  id_phone INT AUTO_INCREMENT  PRIMARY KEY,
  creation_date VARCHAR(250) NOT NULL,
  name VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  price VARCHAR(250) NOT NULL,
  color VARCHAR(250) NOT NULL
);
